"""
Phase 13 Automated Validation Suite: Proactive Stateful Elicitation (Tasks 13.8 - 13.12).

Validates:
- 13.8: Agent's first message on each pending section is proactive and generated by the agent,
        not preceded by user queries about that topic.
- 13.9: Completion Gate: conversation CANNOT reach node_tax_computation while any catalog
        section remains in sections_pending.
- 13.10: Short-Circuit Interception: user attempts to skip ahead ("just calculate my tax")
         are intercepted with a polite redirection back to the active section.
- 13.7: Cross-session kill and resume using load_elicitation_state and DB persistence.
- 13.2: Automatic conditional skip rules (80GG with HRA, 80TTB for non-seniors, etc.).
- 13.4: Deterministic parsing of user elicitation responses into declared vs not_applicable.
"""

import pytest
from sqlmodel import Session, SQLModel, create_engine
from sqlmodel.pool import StaticPool

from app.agent.elicitation import (
    CANONICAL_SECTIONS_ORDER,
    SECTION_QUESTIONS,
    evaluate_auto_skips,
    is_short_circuit_attempt,
    parse_elicitation_response,
)
from app.agent.graph import (
    build_tax_planning_graph,
    run_tax_planning_agent,
    step_tax_planning_agent,
)
from app.agent.persistence import (
    load_elicitation_state,
    record_elicited_deduction,
    save_elicitation_step,
)
from app.agent.state import ElicitationState, TaxPlanningState
from app.models.elicitation_progress import ElicitationProgress, ElicitationStateEnum
from app.models.user_declared_deduction import UserDeclaredDeduction


@pytest.fixture(name="memory_session")
def memory_session_fixture():
    engine = create_engine(
        "sqlite:///:memory:",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    SQLModel.metadata.create_all(engine)
    with Session(engine) as session:
        yield session


# ==============================================================================
# Task 13.8: Agent First Message Is Proactive
# ==============================================================================


def test_13_8_agent_first_message_is_proactive_across_profiles():
    """
    Task 13.8: Runs the flow across 3 synthetic profiles; asserts the agent's first
    message on each pending section is generated by the agent, not preceded by any
    user prompt about that topic.
    """
    # Profile A: Standard Salaried Employee
    state_a = TaxPlanningState(
        user_id=101,
        gross_income=1200000.0,
        is_salaried=True,
        salary_slip_data={"basic": 60000.0, "hra": 30000.0, "gross_pay": 100000.0, "employee_pf": 7200.0},
    )

    # Step 1: Agent starts conversation proactively without any user message
    res_1 = step_tax_planning_agent(state_a, user_message=None)
    assert res_1.current_agent_message is not None
    # Must proactively ask about Section 80C (first canonical pending section)
    assert "80C" in res_1.current_agent_message
    assert res_1.elicitation.current_section == "80C"

    # User responds to 80C
    res_2 = step_tax_planning_agent(res_1, user_message="I invest 150000 in PPF and ELSS")
    assert "80C" in res_2.elicitation.sections_answered
    assert res_2.elicitation.sections_answered["80C"]["status"] == "declared"

    # Next message MUST proactively ask about the next pending section (80CCD(1B)), NOT user prompted
    assert res_2.current_agent_message is not None
    assert "80CCD(1B)" in res_2.current_agent_message
    assert res_2.elicitation.current_section == "80CCD(1B)"

    # Profile B: Senior Citizen Consultant (Age >= 60, no salary slip)
    state_b = TaxPlanningState(
        user_id=102,
        gross_income=900000.0,
        is_salaried=False,
        user_profile={"age": 65, "is_senior_citizen": True},
    )
    res_b1 = step_tax_planning_agent(state_b, user_message=None)
    assert res_b1.current_agent_message is not None
    assert "80C" in res_b1.current_agent_message
    # 80TTA should be automatically skipped for senior citizen (80TTB applies instead)
    assert "80TTA" in res_b1.elicitation.sections_skipped

    # Profile C: Salaried Individual without HRA
    state_c = TaxPlanningState(
        user_id=103,
        gross_income=800000.0,
        is_salaried=True,
        salary_slip_data={"basic": 50000.0, "hra": 0.0, "gross_pay": 66667.0},
    )
    res_c1 = step_tax_planning_agent(state_c, user_message=None)
    # HRA 10(13A) should be skipped because salary slip has 0 HRA
    assert "10(13A)" in res_c1.elicitation.sections_skipped
    # 80GG should NOT be skipped because HRA is 0
    assert "80GG" not in res_c1.elicitation.sections_skipped


# ==============================================================================
# Task 13.9: Completion Gate Blocks Tax Computation
# ==============================================================================


def test_13_9_completion_gate_blocks_tax_computation_while_sections_pending():
    """
    Task 13.9: Asserts that a conversation CANNOT reach the tax-computation node
    while any catalog section remains in sections_pending.
    """
    state = TaxPlanningState(
        user_id=201,
        gross_income=1500000.0,
        is_salaried=True,
    )

    # Initial turn: 18 sections pending
    res = step_tax_planning_agent(state, user_message=None)
    assert len(res.elicitation.sections_pending) > 0
    assert "node_tax_computation" not in res.visited_nodes
    assert res.comparison_result is None
    assert res.final_report is None

    # Resolve first section
    res2 = step_tax_planning_agent(res, user_message="150000")
    assert len(res2.elicitation.sections_pending) > 0
    assert "node_tax_computation" not in res2.visited_nodes
    assert res2.comparison_result is None
    assert res2.final_report is None

    # Now create a state where all sections except one are resolved
    res_almost_done = res2.model_copy()
    res_almost_done.elicitation.sections_pending = ["80U"]
    res_almost_done.elicitation.current_section = "80U"

    # User is on the last section: answer it
    res_final = step_tax_planning_agent(res_almost_done, user_message="No")
    assert len(res_final.elicitation.sections_pending) == 0
    assert "node_tax_computation" in res_final.visited_nodes
    assert res_final.comparison_result is not None
    assert res_final.final_report is not None
    assert "recommended_regime" in res_final.final_report


# ==============================================================================
# Task 13.10: Intercept Short-Circuit Attempts
# ==============================================================================


def test_13_10_short_circuit_redirects_to_pending_section():
    """
    Task 13.10: Simulates user trying to skip ahead ("just calculate my tax") before all
    sections are resolved; asserts the agent redirects back to the next pending section.
    """
    state = TaxPlanningState(
        user_id=301,
        gross_income=1200000.0,
        is_salaried=True,
    )
    res_init = step_tax_planning_agent(state, user_message=None)
    assert res_init.elicitation.current_section == "80C"

    # User attempts to short-circuit
    short_circuit_prompts = [
        "just calculate my tax",
        "calculate my tax now please",
        "skip ahead and give me the recommendation",
        "what is my tax liability?",
        "tell me how much tax I owe",
    ]

    for phrase in short_circuit_prompts:
        step_res = step_tax_planning_agent(res_init, user_message=phrase)
        # 1. Tax computation node MUST NOT be visited
        assert "node_tax_computation" not in step_res.visited_nodes
        assert step_res.comparison_result is None
        assert step_res.final_report is None

        # 2. Redirect message must be present and explain why
        assert step_res.redirect_message is not None
        assert "Before we calculate your final tax liability" in step_res.redirect_message
        # 3. Must remind the user about the currently pending section
        assert "Section 80C" in step_res.redirect_message
        assert step_res.elicitation.current_section == "80C"


# ==============================================================================
# Task 13.7 & 13.12: Cross-Session Kill and Resumption
# ==============================================================================


def test_13_7_cross_session_kill_and_resumption(memory_session: Session):
    """
    Task 13.7 / 13.12: Simulates killing the session mid-conversation, restarting it,
    and verifying it resumes from the exact next pending section.
    """
    user_id = 401
    fy = "2025-2026"

    # Step 1: User declares 80C in first session
    record_elicited_deduction(
        session=memory_session,
        user_id=user_id,
        section="80C",
        amount=150000.0,
        status="declared",
        financial_year=fy,
    )

    # Step 2: 80CCD(1B) is answered as not_applicable
    record_elicited_deduction(
        session=memory_session,
        user_id=user_id,
        section="80CCD(1B)",
        amount=0.0,
        status="not_applicable",
        financial_year=fy,
    )

    # Step 3: 80GG is automatically skipped
    save_elicitation_step(
        session=memory_session,
        user_id=user_id,
        section_code="80GG",
        state=ElicitationStateEnum.skipped,
        financial_year=fy,
        skip_reason="Salary slip contains HRA component",
    )

    # --- SESSION KILL: Memory is cleared, new process starts ---

    # Step 4: Resume session by loading state from DB
    resumed_elicitation = load_elicitation_state(
        session=memory_session,
        user_id=user_id,
        financial_year=fy,
    )

    # Verify loaded progress
    assert "80C" in resumed_elicitation.sections_answered
    assert resumed_elicitation.sections_answered["80C"]["amount"] == 150000.0
    assert "80CCD(1B)" in resumed_elicitation.sections_answered
    assert resumed_elicitation.sections_answered["80CCD(1B)"]["status"] == "not_applicable"
    assert "80GG" in resumed_elicitation.sections_skipped
    assert "80C" not in resumed_elicitation.sections_pending
    assert "80CCD(1B)" not in resumed_elicitation.sections_pending
    assert "80GG" not in resumed_elicitation.sections_pending

    # Next pending section must be 80CCD(2) (the 3rd canonical section)
    assert resumed_elicitation.current_section == "80CCD(2)"

    # Step 5: Execute turn using resumed state
    resumed_state = TaxPlanningState(
        user_id=user_id,
        gross_income=1400000.0,
        elicitation=resumed_elicitation,
    )
    turn_res = step_tax_planning_agent(resumed_state, user_message=None)
    assert "80CCD(2)" in turn_res.current_agent_message


# ==============================================================================
# Task 13.2: Automatic Conditional Skip Rules
# ==============================================================================


def test_13_2_automatic_conditional_skip_evaluator():
    """
    Task 13.2: Verifies that conditional skip rules fire deterministically:
    - 80GG skipped if HRA present
    - 10(13A) skipped if no HRA
    - 80TTB skipped if not senior citizen
    - 80TTA skipped if senior citizen
    """
    # 1. HRA recipient
    state_hra = TaxPlanningState(
        gross_income=1000000.0,
        salary_slip_data={"basic": 50000.0, "hra": 25000.0},
        user_profile={"age": 30},
    )
    skips_hra = evaluate_auto_skips(state_hra, CANONICAL_SECTIONS_ORDER)
    assert "80GG" in skips_hra
    assert "10(13A)" not in skips_hra
    assert "80TTB" in skips_hra  # age 30 is not senior citizen

    # 2. Non-HRA recipient
    state_no_hra = TaxPlanningState(
        gross_income=1000000.0,
        salary_slip_data={"basic": 50000.0, "hra": 0.0},
        user_profile={"age": 30},
    )
    skips_no_hra = evaluate_auto_skips(state_no_hra, CANONICAL_SECTIONS_ORDER)
    assert "10(13A)" in skips_no_hra
    assert "80GG" not in skips_no_hra

    # 3. Senior Citizen
    state_senior = TaxPlanningState(
        gross_income=800000.0,
        user_profile={"age": 68},
    )
    skips_senior = evaluate_auto_skips(state_senior, CANONICAL_SECTIONS_ORDER)
    assert "80TTA" in skips_senior
    assert "80TTB" not in skips_senior


# ==============================================================================
# Task 13.4: Natural Language Response Parsing
# ==============================================================================


def test_13_4_natural_language_response_parsing():
    """
    Task 13.4: Verifies response parsing maps amounts to declared and negations to not_applicable.
    """
    # Numeric amounts
    status, amt, _ = parse_elicitation_response("I put 150000 in PPF", "80C")
    assert status == "declared"
    assert amt == 150000.0

    status, amt, _ = parse_elicitation_response("₹50,000 in NPS", "80CCD(1B)")
    assert status == "declared"
    assert amt == 50000.0

    status, amt, _ = parse_elicitation_response("25k health insurance", "80D")
    assert status == "declared"
    assert amt == 25000.0

    # Negative / None responses
    for neg in ["No", "None", "N/A", "no deductions", "I don't have this", "zero", "nil"]:
        status, amt, _ = parse_elicitation_response(neg, "80G")
        assert status == "not_applicable"
        assert amt == 0.0
