"""create_phase1_models

Revision ID: 22ed5cc19d46
Revises: 
Create Date: 2026-09-12 15:42:39.474906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '22ed5cc19d46'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_income', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('tax_rule_versions',
    sa.Column('financial_year', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('version_tag', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_rule_versions_financial_year'), 'tax_rule_versions', ['financial_year'], unique=True)
    op.create_table('users',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('pan', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_pan'), 'users', ['pan'], unique=False)
    op.create_table('accounts',
    sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('bank_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('account_number_mask', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('account_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('current_balance', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('salary_slips',
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('financial_year', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('basic', sa.Float(), nullable=False),
    sa.Column('hra', sa.Float(), nullable=False),
    sa.Column('lta', sa.Float(), nullable=False),
    sa.Column('special_allowance', sa.Float(), nullable=False),
    sa.Column('other_allowances', sa.Float(), nullable=False),
    sa.Column('gross_pay', sa.Float(), nullable=False),
    sa.Column('employee_pf', sa.Float(), nullable=False),
    sa.Column('employer_pf', sa.Float(), nullable=False),
    sa.Column('professional_tax', sa.Float(), nullable=False),
    sa.Column('tds', sa.Float(), nullable=False),
    sa.Column('other_deductions', sa.Float(), nullable=False),
    sa.Column('total_deductions', sa.Float(), nullable=False),
    sa.Column('net_pay', sa.Float(), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('is_gross_valid', sa.Boolean(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('raw_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_slips_needs_review'), 'salary_slips', ['needs_review'], unique=False)
    op.create_index(op.f('ix_salary_slips_user_id'), 'salary_slips', ['user_id'], unique=False)
    op.create_table('tax_computations',
    sa.Column('financial_year', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('gross_income', sa.Float(), nullable=False),
    sa.Column('old_regime_taxable_income', sa.Float(), nullable=False),
    sa.Column('old_regime_tax', sa.Float(), nullable=False),
    sa.Column('old_regime_cess', sa.Float(), nullable=False),
    sa.Column('old_regime_total_liability', sa.Float(), nullable=False),
    sa.Column('new_regime_taxable_income', sa.Float(), nullable=False),
    sa.Column('new_regime_tax', sa.Float(), nullable=False),
    sa.Column('new_regime_cess', sa.Float(), nullable=False),
    sa.Column('new_regime_total_liability', sa.Float(), nullable=False),
    sa.Column('recommended_regime', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('tax_savings', sa.Float(), nullable=False),
    sa.Column('deductions_applied', sa.JSON(), nullable=True),
    sa.Column('computation_breakdown', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_computations_financial_year'), 'tax_computations', ['financial_year'], unique=False)
    op.create_index(op.f('ix_tax_computations_user_id'), 'tax_computations', ['user_id'], unique=False)
    op.create_table('user_declared_deductions',
    sa.Column('financial_year', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('section', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_declared_deductions_financial_year'), 'user_declared_deductions', ['financial_year'], unique=False)
    op.create_index(op.f('ix_user_declared_deductions_section'), 'user_declared_deductions', ['section'], unique=False)
    op.create_index(op.f('ix_user_declared_deductions_user_id'), 'user_declared_deductions', ['user_id'], unique=False)
    op.create_table('statement_uploads',
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('file_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('parse_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('parse_confidence', sa.Float(), nullable=True),
    sa.Column('balance_reconciled', sa.Boolean(), nullable=False),
    sa.Column('opening_balance', sa.Float(), nullable=True),
    sa.Column('closing_balance', sa.Float(), nullable=True),
    sa.Column('statement_start_date', sa.Date(), nullable=True),
    sa.Column('statement_end_date', sa.Date(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('raw_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statement_uploads_account_id'), 'statement_uploads', ['account_id'], unique=False)
    op.create_index(op.f('ix_statement_uploads_file_hash'), 'statement_uploads', ['file_hash'], unique=False)
    op.create_index(op.f('ix_statement_uploads_needs_review'), 'statement_uploads', ['needs_review'], unique=False)
    op.create_index(op.f('ix_statement_uploads_parse_status'), 'statement_uploads', ['parse_status'], unique=False)
    op.create_index(op.f('ix_statement_uploads_user_id'), 'statement_uploads', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('cleaned_description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_type', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('reference_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('parse_confidence', sa.Float(), nullable=True),
    sa.Column('parse_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('balance_reconciled', sa.Boolean(), nullable=False),
    sa.Column('category_confidence', sa.Float(), nullable=True),
    sa.Column('is_self_transfer', sa.Boolean(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['statement_uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_category_id'), 'transactions', ['category_id'], unique=False)
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_is_self_transfer'), 'transactions', ['is_self_transfer'], unique=False)
    op.create_index(op.f('ix_transactions_needs_review'), 'transactions', ['needs_review'], unique=False)
    op.create_index(op.f('ix_transactions_reference_number'), 'transactions', ['reference_number'], unique=False)
    op.create_index(op.f('ix_transactions_upload_id'), 'transactions', ['upload_id'], unique=False)
    op.create_table('reconciliation_flags',
    sa.Column('salary_slip_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('flag_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('expected_amount', sa.Float(), nullable=True),
    sa.Column('actual_amount', sa.Float(), nullable=True),
    sa.Column('difference', sa.Float(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('user_note', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['salary_slip_id'], ['salary_slips.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_flags_salary_slip_id'), 'reconciliation_flags', ['salary_slip_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_flags_status'), 'reconciliation_flags', ['status'], unique=False)
    op.create_index(op.f('ix_reconciliation_flags_transaction_id'), 'reconciliation_flags', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_flags_user_id'), 'reconciliation_flags', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliation_flags_user_id'), table_name='reconciliation_flags')
    op.drop_index(op.f('ix_reconciliation_flags_transaction_id'), table_name='reconciliation_flags')
    op.drop_index(op.f('ix_reconciliation_flags_status'), table_name='reconciliation_flags')
    op.drop_index(op.f('ix_reconciliation_flags_salary_slip_id'), table_name='reconciliation_flags')
    op.drop_table('reconciliation_flags')
    op.drop_index(op.f('ix_transactions_upload_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_reference_number'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_needs_review'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_is_self_transfer'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_statement_uploads_user_id'), table_name='statement_uploads')
    op.drop_index(op.f('ix_statement_uploads_parse_status'), table_name='statement_uploads')
    op.drop_index(op.f('ix_statement_uploads_needs_review'), table_name='statement_uploads')
    op.drop_index(op.f('ix_statement_uploads_file_hash'), table_name='statement_uploads')
    op.drop_index(op.f('ix_statement_uploads_account_id'), table_name='statement_uploads')
    op.drop_table('statement_uploads')
    op.drop_index(op.f('ix_user_declared_deductions_user_id'), table_name='user_declared_deductions')
    op.drop_index(op.f('ix_user_declared_deductions_section'), table_name='user_declared_deductions')
    op.drop_index(op.f('ix_user_declared_deductions_financial_year'), table_name='user_declared_deductions')
    op.drop_table('user_declared_deductions')
    op.drop_index(op.f('ix_tax_computations_user_id'), table_name='tax_computations')
    op.drop_index(op.f('ix_tax_computations_financial_year'), table_name='tax_computations')
    op.drop_table('tax_computations')
    op.drop_index(op.f('ix_salary_slips_user_id'), table_name='salary_slips')
    op.drop_index(op.f('ix_salary_slips_needs_review'), table_name='salary_slips')
    op.drop_table('salary_slips')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_pan'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tax_rule_versions_financial_year'), table_name='tax_rule_versions')
    op.drop_table('tax_rule_versions')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
